### ISSUE TITLE
Why does rkos use bfd linker instead of lld?

### ISSUE THREAD

**Issue by ssfdust** [open-rust-initiative/rkos#19]
Since the kernel is compiled with clang and llvm, would lld be a better choice for rkos, which is the default linker for llvm(maybe faster)？
Nowdays, lld can link the kernel, according to https://www.kernel.org/doc/html/latest/kbuild/llvm.html.

**Comment by xyyy1420** [comment]
Thank you for your question. Using lld is indeed a better choice, but the main purpose of using clang and llvm at present is to compile the linux kernel with rust support. The lld linker is not necessary to achieve this goal, so it is not currently used, but one thing is certain is that we will make lld the default linker as soon as possible. Thank you again.
